### ISSUE TITLE
Can only add one item

### ISSUE THREAD

**Issue by talbet** [salted-herring/silverstripe-shortlist#2]
I am having trouble implementing this module (which is really useful, thanks for taking the time to write it)

I can only add one item to the shortlist, any additional pages I try to add get skipped. Looking through the code I found that in `AddToShortlistAction.php` the function the checks for existing items uses the filterAny method:

``` php
// check whether the itme is already in the list
// before attempting to add it.
$existing = $shortlist->ShortListItems()->filterAny(
    array('ItemID' => $ID, 'ItemType' => $type)
);

// Item already exists, we're not going to add it again.
if ($existing->count() == 1) {
    return $shortlist;
}
```

This means that if I try to add an item with the same Class as one that is already on the shortlist it will be added by the filterAny and then the early return will run.

Is this intentional, as using filter instead or filterAny seems like it would build the desired list?

**Comment by simonwinter** [comment]
Thanks @talbet I'll have a look when I get a chance. Soon I promise :)

**Comment by simonwinter** [comment]
Hi @talbet.

I agree with you, it should really be filter. Have changed the code. Please give it a pull & let me know if this solves your problem.

Thanks.

**Comment by talbet** [comment]
Thanks, it's working for me now.
